"""Curated articles, docs, and courses mapped to skills and curriculum days."""

# Each resource: title, url, resource_type, skill_slug?, day_number?, week_number?,
# description, is_primary, order

RESOURCES = [
    # ——— Python ———
    {
        "title": "Python Data Model",
        "url": "https://docs.python.org/3/reference/datamodel.html",
        "resource_type": "docs",
        "skill_slug": "python",
        "day_number": 1,
        "description": "Official reference for objects, types, and special methods.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Fluent Python (Book site)",
        "url": "https://www.fluentpython.com/",
        "resource_type": "book",
        "skill_slug": "python",
        "week_number": 1,
        "description": "Deep dive companion for advanced Python weeks.",
        "is_primary": False,
        "order": 2,
    },
    {
        "title": "Real Python — Decorators",
        "url": "https://realpython.com/primer-on-python-decorators/",
        "resource_type": "article",
        "skill_slug": "python",
        "day_number": 5,
        "description": "Practical decorator patterns with functools.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "PEP 484 — Type Hints",
        "url": "https://peps.python.org/pep-0484/",
        "resource_type": "docs",
        "skill_slug": "python",
        "day_number": 10,
        "description": "Canonical typing foundations.",
        "is_primary": True,
        "order": 1,
    },
    # ——— DSA ———
    {
        "title": "NeetCode Roadmap",
        "url": "https://neetcode.io/roadmap",
        "resource_type": "course",
        "skill_slug": "algorithms-data-structures",
        "week_number": 3,
        "description": "Pattern-based problem roadmap for interview DSA.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "CP-Algorithms",
        "url": "https://cp-algorithms.com/",
        "resource_type": "docs",
        "skill_slug": "algorithms-data-structures",
        "week_number": 4,
        "description": "Reference implementations and complexity notes.",
        "is_primary": False,
        "order": 2,
    },
    {
        "title": "Dynamic Programming Patterns",
        "url": "https://leetcode.com/discuss/general-discussion/458695/dynamic-programming-patterns",
        "resource_type": "article",
        "skill_slug": "algorithms-data-structures",
        "day_number": 27,
        "description": "Common DP families for interview prep.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Backend / Django ———
    {
        "title": "Django REST Framework Tutorial",
        "url": "https://www.django-rest-framework.org/tutorial/1-serialization/",
        "resource_type": "docs",
        "skill_slug": "django",
        "day_number": 34,
        "description": "Official DRF path for serializers and viewsets.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "HTTP Semantics (RFC 9110)",
        "url": "https://www.rfc-editor.org/rfc/rfc9110",
        "resource_type": "docs",
        "skill_slug": "backend-engineering",
        "day_number": 31,
        "description": "Authoritative HTTP method and status semantics.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Twelve-Factor App",
        "url": "https://12factor.net/",
        "resource_type": "article",
        "skill_slug": "backend-engineering",
        "week_number": 5,
        "description": "Production service hygiene checklist.",
        "is_primary": False,
        "order": 2,
    },
    # ——— PostgreSQL ———
    {
        "title": "PostgreSQL EXPLAIN",
        "url": "https://www.postgresql.org/docs/current/using-explain.html",
        "resource_type": "docs",
        "skill_slug": "postgresql",
        "day_number": 41,
        "description": "Official guide to reading query plans.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Use The Index, Luke",
        "url": "https://use-the-index-luke.com/",
        "resource_type": "course",
        "skill_slug": "postgresql",
        "week_number": 6,
        "description": "Index design course for SQL engines.",
        "is_primary": False,
        "order": 2,
    },
    {
        "title": "Postgres Isolation Levels",
        "url": "https://www.postgresql.org/docs/current/transaction-iso.html",
        "resource_type": "docs",
        "skill_slug": "postgresql",
        "day_number": 42,
        "description": "Transaction isolation and anomalies.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Redis / distributed ———
    {
        "title": "Redis Caching Patterns",
        "url": "https://redis.io/docs/latest/develop/clients/patterns/",
        "resource_type": "docs",
        "skill_slug": "redis",
        "day_number": 46,
        "description": "Official client patterns including cache-aside.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Celery First Steps",
        "url": "https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html",
        "resource_type": "docs",
        "skill_slug": "redis",
        "day_number": 47,
        "description": "Background jobs, retries, and acknowledgements.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Designing Data-Intensive Applications (overview)",
        "url": "https://dataintensive.net/",
        "resource_type": "book",
        "skill_slug": "distributed-systems",
        "week_number": 7,
        "description": "Canonical book for reliability and data systems.",
        "is_primary": True,
        "order": 1,
    },
    # ——— System design ———
    {
        "title": "System Design Primer",
        "url": "https://github.com/donnemartin/system-design-primer",
        "resource_type": "course",
        "skill_slug": "system-design",
        "week_number": 8,
        "description": "Structured primer with common interview designs.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "AWS Well-Architected",
        "url": "https://aws.amazon.com/architecture/well-architected/",
        "resource_type": "docs",
        "skill_slug": "aws",
        "day_number": 79,
        "description": "Operational excellence and reliability pillars.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Testing / performance ———
    {
        "title": "pytest Documentation",
        "url": "https://docs.pytest.org/en/stable/",
        "resource_type": "docs",
        "skill_slug": "testing",
        "day_number": 75,
        "description": "Fixtures, parametrize, and plugin ecosystem.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Google SRE — Handling Overload",
        "url": "https://sre.google/sre-book/handling-overload/",
        "resource_type": "article",
        "skill_slug": "performance-engineering",
        "day_number": 100,
        "description": "Load shedding and overload control for elite ops.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Google SRE — Managing Incidents",
        "url": "https://sre.google/sre-book/managing-incidents/",
        "resource_type": "article",
        "skill_slug": "software-architecture",
        "day_number": 98,
        "description": "Incident command and communication patterns.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Google SRE — Postmortem Culture",
        "url": "https://sre.google/sre-book/postmortem-culture/",
        "resource_type": "article",
        "skill_slug": "software-architecture",
        "day_number": 104,
        "description": "Blameless postmortems that produce learning.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Cloud / K8s ———
    {
        "title": "Kubernetes Concepts",
        "url": "https://kubernetes.io/docs/concepts/",
        "resource_type": "docs",
        "skill_slug": "kubernetes",
        "day_number": 109,
        "description": "Pods, services, probes, and controllers.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Docker Production Best Practices",
        "url": "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
        "resource_type": "docs",
        "skill_slug": "docker",
        "day_number": 73,
        "description": "Image hygiene for production containers.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Interview / communication ———
    {
        "title": "Staff Engineer (book site)",
        "url": "https://staffeng.com/",
        "resource_type": "book",
        "skill_slug": "communication",
        "day_number": 117,
        "description": "Leveling narratives and staff-shaped impact.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Amazon Leadership Principles (behavioral prep)",
        "url": "https://www.amazon.jobs/content/en/our-workplace/leadership-principles",
        "resource_type": "article",
        "skill_slug": "interview-skills",
        "day_number": 115,
        "description": "Behavioral story framing used widely in interviews.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "Architecture Decision Records",
        "url": "https://adr.github.io/",
        "resource_type": "docs",
        "skill_slug": "software-architecture",
        "day_number": 105,
        "description": "Lightweight ADR templates for proof-of-work.",
        "is_primary": True,
        "order": 1,
    },
    # ——— Phase 4 skill primaries (no day) ———
    {
        "title": "Idempotency patterns",
        "url": "https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/",
        "resource_type": "article",
        "skill_slug": "backend-engineering",
        "day_number": 102,
        "description": "Safe retries for distributed APIs.",
        "is_primary": True,
        "order": 1,
    },
    {
        "title": "FastAPI docs (contrast track)",
        "url": "https://fastapi.tiangolo.com/",
        "resource_type": "docs",
        "skill_slug": "fastapi",
        "week_number": 5,
        "description": "Optional FastAPI depth alongside Django track.",
        "is_primary": True,
        "order": 1,
    },
]
