def build_brain_teasers() -> list[dict]:
    raw = [
        {"question": "A man pushes his car to a hotel and tells the owner he is bankrupt. What happened?", "answer": "Monopoly", "explanation": "He landed on a hotel space in the board game Monopoly.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A woman shoots her husband, then holds him underwater for five minutes. Next she hangs him. Later they go out for dinner. How?", "answer": "She is a photographer", "explanation": "She developed photos, soaked prints, and hung them to dry.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "A man lives on the 20th floor. Every day he takes the elevator to the ground floor. Going up, he rides to the 10th and walks the rest—except on rainy days. Why?", "answer": "He is too short", "explanation": "He can only reach the 10th-floor button; on rainy days he has an umbrella.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "You enter a room with a match, a kerosene lamp, a fireplace, and a candle. What do you light first?", "answer": "The match", "explanation": "Nothing else can be lit until the match is struck.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A father and son crash. The father dies. The son is rushed to surgery. The surgeon says 'I cannot operate—he is my son.' Who is the surgeon?", "answer": "His mother", "explanation": "The surgeon is the boy's mother.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A man is found dead in a field with an unopened package. How did he die?", "answer": "Parachute failure", "explanation": "The unopened package was his parachute.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "Two coins total 30 cents. One is not a nickel. What are they?", "answer": "A quarter and a nickel", "explanation": "Only one coin is not a nickel; the other is.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "How can you drop a raw egg onto concrete without cracking it?", "answer": "Concrete won't crack", "explanation": "Concrete is too hard to crack from a falling egg.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A bus driver goes the wrong way on a one-way street without breaking the law. How?", "answer": "He was walking", "explanation": "He was not driving the bus at the time.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "What can you hold in your right hand but never in your left?", "answer": "Your left elbow", "explanation": "Your left elbow cannot be reached by your left hand.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "A man bets he can predict the score of any football game before it starts. How?", "answer": "0-0", "explanation": "Every game starts tied at zero.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "You draw a line. Without touching it, how do you make it longer?", "answer": "Draw a shorter line beside it", "explanation": "A shorter adjacent line makes the original look longer.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A cowboy rides into town on Friday, stays three days, and leaves on Friday. How?", "answer": "His horse is named Friday", "explanation": "Friday refers to the horse, not the day.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What disappears the moment you say its name?", "answer": "Silence", "explanation": "Speaking breaks the silence.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A plane crashes on the border of the US and Canada. Where do they bury the survivors?", "answer": "Nowhere", "explanation": "Survivors are not buried.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "How many times can you subtract 5 from 25?", "answer": "Once", "explanation": "After the first subtraction you are subtracting from 20.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A clerk at a butcher shop is 5'10\" and wears size 13 shoes. What does he weigh?", "answer": "Meat", "explanation": "He weighs meat for customers.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "Before Mount Everest was discovered, what was the highest mountain?", "answer": "Mount Everest", "explanation": "It was still the tallest; it had not been discovered yet.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "What gets wetter the more it dries?", "answer": "A towel", "explanation": "A towel absorbs water as it dries things.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A man builds a house with all four sides facing south. A bear walks by. What color is the bear?", "answer": "White", "explanation": "Only at the North Pole can all walls face south; polar bears are white.", "category": "lateral_thinking", "difficulty": "hard"},
        {"question": "You have a 3-gallon and 5-gallon jug. How do you measure exactly 4 gallons?", "answer": "Fill 5, pour into 3, empty 3, pour remaining 2 into 3, fill 5, top off 3", "explanation": "Classic jug-pouring sequence yields exactly 4 gallons in the 5-gallon jug.", "category": "lateral_thinking", "difficulty": "hard"},
        {"question": "A man is looking at a photo. 'Brothers and sisters I have none, but that man's father is my father's son.' Who is in the photo?", "answer": "His son", "explanation": "My father's son is me; so the man is my son.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What has keys but no locks, space but no room, and you can enter but not go inside?", "answer": "A keyboard", "explanation": "Computer keyboard fits all clues.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "What goes up a chimney down but not down a chimney up?", "answer": "An umbrella", "explanation": "An open umbrella won't fit down a chimney.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A man rode into town on Tuesday and left two days later on Tuesday. How?", "answer": "He rode a horse named Tuesday", "explanation": "Tuesday is the horse's name.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What kind of coat is always wet when you put it on?", "answer": "A coat of paint", "explanation": "Paint coat is liquid.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A woman has seven children. Half are boys. How is this possible?", "answer": "All are boys", "explanation": "The other half are also boys—wordplay on 'half'.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What can you catch but not throw?", "answer": "A cold", "explanation": "You catch a cold, not throw it.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A man walks into a bar and asks for a glass of water. The bartender pulls a gun. The man says thanks and leaves. Why?", "answer": "Hiccups", "explanation": "The gun scare cured his hiccups.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What has a face and two hands but no arms or legs?", "answer": "A clock", "explanation": "Clock face and hands.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "A man is arrested at the border with an empty bicycle. How did he smuggle diamonds?", "answer": "Inside the bicycle", "explanation": "Diamonds were hidden in the bike frame.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "A man is found dead in a phone booth with shattered glass. How did he die?", "answer": "Fishing accident", "explanation": "A fisherman cast his line through the booth and startled him.", "category": "lateral_thinking", "difficulty": "hard"},
        {"question": "Three switches control three bulbs in another room. You may inspect once. How do you map each switch?", "answer": "Turn one on briefly, off; turn second on; enter", "explanation": "Warm-off bulb matches first switch, lit bulb second, cold bulb third.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "Five pirates split 100 gold coins by majority vote; ties go to the proposer. What does the smartest pirate offer?", "answer": "98 to pirate 2, 1 to pirate 4, 1 to pirate 5", "explanation": "Backward induction in the pirate game yields this distribution.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "You have 12 identical-looking balls; one is heavier. Minimum weighings on a balance scale?", "answer": "3", "explanation": "Three weighings suffice via ternary partitioning.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "Two guards: one always lies, one always tells truth. One door is freedom. One question?", "answer": "Ask either: 'Would the other guard say this door is freedom?'", "explanation": "Then choose the opposite door.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "A says 'B is lying.' B says 'C is lying.' C says 'A and B are lying.' Who is telling the truth?", "answer": "B", "explanation": "If B lies, A tells truth; C's claim fails. Only B consistent.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Four people cross a bridge in 17 minutes max. Times: 1, 2, 5, 10. Two at a time; slower sets pace. Minimum?", "answer": "17 minutes", "explanation": "1+2 over, 1 back, 5+10 over, 2 back, 1+2 over.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "In a room of 23 people, probability at least two share a birthday?", "answer": "About 50%", "explanation": "Birthday paradox: 23 gives roughly 50.7%.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "You have 9 dots in a 3x3 grid. Connect all with 4 straight lines without lifting pen?", "answer": "Yes, extend lines beyond grid", "explanation": "Classic nine-dot puzzle requires thinking outside the box.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Three boxes: apples, oranges, mixed. All labels wrong. One fruit from one box to fix labels?", "answer": "Pull from 'mixed' box", "explanation": "That box is pure; deduce the rest from wrong labels.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Five hats: 3 black, 2 white. Three prisoners see others' hats, not own. First to deduce wins. How?", "answer": "They reason about silence", "explanation": "If anyone saw two white hats they'd speak; chain of inference follows.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "You flip a fair coin until heads. Expected number of flips?", "answer": "2", "explanation": "Geometric distribution with p=0.5 has mean 1/p = 2.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Monty Hall: 3 doors, 1 car. Host opens a goat door. Should you switch?", "answer": "Yes", "explanation": "Switching wins 2/3 of the time.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "A snail climbs 3 feet by day, slips 2 by night up a 30-foot well. Days to escape?", "answer": "28", "explanation": "Reaches 27 on day 27, escapes day 28 without slipping back.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Four cards show D, F, 3, 7. Rule: vowel on one side means even number on other. Minimum cards to flip?", "answer": "D and 3", "explanation": "Test vowel and odd number cases.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "Island of knights (truth) and knaves (lie). A says 'We are both knaves.' What are they?", "answer": "A is knave, B is knight", "explanation": "A cannot truthfully claim both knaves.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "You have wolves and chickens to cross a river. Boat holds you plus one. Wolves eat chickens if left alone. Minimum trips?", "answer": "7", "explanation": "Standard river-crossing with constraints.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "A lily pad doubles daily and covers a pond in 30 days. When is it half covered?", "answer": "Day 29", "explanation": "One day before full coverage it was half.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "Three gods: True, False, Random answer randomly. Three yes/no questions to identify them?", "answer": "Yes, with careful encoding", "explanation": "Known solution uses nested questions about each other's answers.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", "answer": "5 minutes", "explanation": "Each machine makes one widget in 5 minutes.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "A bat and ball cost $1.10. Bat costs $1 more than ball. Ball cost?", "answer": "$0.05", "explanation": "Ball $0.05, bat $1.05.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "You are in a dark cave with 100 coins: 30 heads-up. Blindfolded, split into two piles with equal heads?", "answer": "Flip coins in one pile", "explanation": "If pile A has h heads, flip all in A to match pile B's heads count.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "If you have me, you want to share me. If you share me, you no longer have me. What am I?", "answer": "A secret", "explanation": "Secrets disappear when shared.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "Mary's father has five daughters: Nana, Nene, Nini, Nono. What is the fifth daughter's name?", "answer": "Mary", "explanation": "Mary is named in the question.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "You have 8 balls, one heavier. Minimum weighings on a balance scale?", "answer": "2", "explanation": "Two weighings suffice with ternary split.", "category": "logic_puzzle", "difficulty": "medium"},
        {"question": "100 prisoners in line wear black or white hats. Each sees ahead only. Strategy to save 99?", "answer": "Parity protocol", "explanation": "First prisoner encodes parity; others deduce their hat color.", "category": "logic_puzzle", "difficulty": "hard"},
        {"question": "What has a head, a tail, is brown, and has no legs?", "answer": "A penny", "explanation": "A coin has head and tail sides.", "category": "riddle", "difficulty": "easy"},
        {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "The letter M", "explanation": "Count the letter M in each phrase.", "category": "riddle", "difficulty": "easy"},
        {"question": "I speak without a mouth and hear without ears. I have no body but come alive with wind. What am I?", "answer": "An echo", "explanation": "Echoes carry sound without physical form.", "category": "riddle", "difficulty": "medium"},
        {"question": "The more you take, the more you leave behind. What am I?", "answer": "Footsteps", "explanation": "Walking leaves more steps behind you.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has cities but no houses, forests but no trees, and rivers but no water?", "answer": "A map", "explanation": "Maps represent geography symbolically.", "category": "riddle", "difficulty": "easy"},
        {"question": "What can travel around the world while staying in a corner?", "answer": "A stamp", "explanation": "Stamps sit in corners of envelopes.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has hands but cannot clap?", "answer": "A clock", "explanation": "Clock hands indicate time.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has a neck but no head?", "answer": "A bottle", "explanation": "Bottles have necks.", "category": "riddle", "difficulty": "easy"},
        {"question": "What runs but never walks, has a mouth but never talks?", "answer": "A river", "explanation": "Rivers run and have mouths at deltas.", "category": "riddle", "difficulty": "easy"},
        {"question": "What belongs to you but others use it more?", "answer": "Your name", "explanation": "Others say your name more often than you do.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has one eye but cannot see?", "answer": "A needle", "explanation": "The eye of a needle is a hole.", "category": "riddle", "difficulty": "easy"},
        {"question": "What is full of holes but still holds water?", "answer": "A sponge", "explanation": "Sponges are porous and absorbent.", "category": "riddle", "difficulty": "easy"},
        {"question": "What goes up but never comes down?", "answer": "Your age", "explanation": "Age only increases.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has words but never speaks?", "answer": "A book", "explanation": "Books contain written words.", "category": "riddle", "difficulty": "easy"},
        {"question": "What is always in front of you but cannot be seen?", "answer": "The future", "explanation": "The future lies ahead but is unseen.", "category": "riddle", "difficulty": "easy"},
        {"question": "What breaks yet never falls, and falls yet never breaks?", "answer": "Day and night", "explanation": "Day breaks; night falls.", "category": "riddle", "difficulty": "medium"},
        {"question": "I have branches but no fruit, trunk, or leaves. What am I?", "answer": "A bank", "explanation": "Banks have branch offices.", "category": "riddle", "difficulty": "medium"},
        {"question": "What is so fragile that saying its name breaks it?", "answer": "Silence", "explanation": "Speaking ends silence.", "category": "riddle", "difficulty": "easy"},
        {"question": "What has a thumb and four fingers but is not alive?", "answer": "A glove", "explanation": "Gloves mimic hand shape.", "category": "riddle", "difficulty": "easy"},
        {"question": "What can fill a room but takes up no space?", "answer": "Light", "explanation": "Light illuminates without occupying volume.", "category": "riddle", "difficulty": "medium"},
        {"question": "What has legs but cannot walk?", "answer": "A table", "explanation": "Furniture has legs.", "category": "riddle", "difficulty": "easy"},
        {"question": "What invention lets you look through a wall?", "answer": "A window", "explanation": "Windows are openings in walls.", "category": "riddle", "difficulty": "easy"},
        {"question": "What gets sharper the more you use it?", "answer": "Your brain", "explanation": "Practice improves mental acuity.", "category": "riddle", "difficulty": "medium"},
        {"question": "What has a heart that doesn't beat?", "answer": "An artichoke", "explanation": "Artichokes have a heart-shaped core.", "category": "riddle", "difficulty": "medium"},
        {"question": "I have lakes with no water, mountains with no stone, cities with no people. What am I?", "answer": "A map", "explanation": "Maps depict features symbolically.", "category": "riddle", "difficulty": "medium"},
        {"question": "What has four wheels and flies?", "answer": "A garbage truck", "explanation": "Truck has wheels; flies refers to garbage flies.", "category": "riddle", "difficulty": "easy"},
        {"question": "I am not alive, but I grow; I don't have lungs, but I need air; I don't have a mouth, but water kills me. What am I?", "answer": "Fire", "explanation": "Fire grows, needs oxygen, extinguished by water.", "category": "riddle", "difficulty": "hard"},
        {"question": "The maker sells it, the buyer never uses it, the user never knows. What is it?", "answer": "A coffin", "explanation": "Made by carpenter, bought by family, occupant unaware.", "category": "riddle", "difficulty": "medium"},
        {"question": "What can you hold without ever touching?", "answer": "A conversation", "explanation": "You hold a conversation figuratively.", "category": "riddle", "difficulty": "medium"},
        {"question": "What building has the most stories?", "answer": "A library", "explanation": "Books have stories.", "category": "riddle", "difficulty": "easy"},
        {"question": "Think of a number. Double it. Add 10. Halve it. Subtract original. Result?", "answer": "5", "explanation": "Algebra: ((2x+10)/2)-x = 5 always.", "category": "math_trick", "difficulty": "easy"},
        {"question": "Multiply 34 by 11 mentally. Result?", "answer": "374", "explanation": "Split digits, add for middle: 3, 3+4, 4.", "category": "math_trick", "difficulty": "easy"},
        {"question": "Square a number ending in 5: 35 squared?", "answer": "1225", "explanation": "Multiply tens digit by (tens+1), append 25.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What is 1/2 of 2/3 of 3/4 of 4/5 of 100?", "answer": "10", "explanation": "Fractions cancel sequentially leaving 10.", "category": "math_trick", "difficulty": "medium"},
        {"question": "Add 1 to 999. How many carries occur?", "answer": "3", "explanation": "999+1 produces three carries.", "category": "math_trick", "difficulty": "medium"},
        {"question": "How many squares on a standard 8x8 chessboard?", "answer": "204", "explanation": "Sum of k^2 for k=1..8.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What is 7^0?", "answer": "1", "explanation": "Any nonzero number to power 0 is 1.", "category": "math_trick", "difficulty": "easy"},
        {"question": "If 3 cats catch 3 mice in 3 minutes, how many cats catch 100 mice in 100 minutes?", "answer": "3", "explanation": "Rate is 1 mouse per cat per minute.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What is 0.999... equal to?", "answer": "1", "explanation": "Repeating decimal equals 1 exactly.", "category": "math_trick", "difficulty": "medium"},
        {"question": "Quick: 99 x 101?", "answer": "9999", "explanation": "Difference of squares: 100^2 - 1.", "category": "math_trick", "difficulty": "easy"},
        {"question": "Sum of first 100 positive integers?", "answer": "5050", "explanation": "n(n+1)/2 = 100*101/2.", "category": "math_trick", "difficulty": "easy"},
        {"question": "How many trailing zeros in 25!?", "answer": "6", "explanation": "Count factors of 5 in factorial.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What is the only even prime?", "answer": "2", "explanation": "2 is divisible only by 1 and itself.", "category": "math_trick", "difficulty": "easy"},
        {"question": "If you multiply all numbers on a phone keypad, result?", "answer": "0", "explanation": "Keypad includes 0.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What is 2^10?", "answer": "1024", "explanation": "Powers of 2: 2^10 = 1024.", "category": "math_trick", "difficulty": "easy"},
        {"question": "How many degrees in a triangle on a sphere?", "answer": "More than 180", "explanation": "Spherical geometry exceeds Euclidean sum.", "category": "math_trick", "difficulty": "hard"},
        {"question": "What is sqrt(0.25)?", "answer": "0.5", "explanation": "Square root of 1/4 is 1/2.", "category": "math_trick", "difficulty": "easy"},
        {"question": "If a pizza is cut into 8 slices and you eat 3, what fraction remains?", "answer": "5/8", "explanation": "Eight minus three leaves five eighths.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What is the sum of angles in a hexagon?", "answer": "720", "explanation": "(6-2)*180 = 720 degrees.", "category": "math_trick", "difficulty": "medium"},
        {"question": "Double a number, add 8, divide by 2, subtract original. Always get?", "answer": "4", "explanation": "((2x+8)/2)-x = 4.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What is 15% of 200?", "answer": "30", "explanation": "0.15 * 200 = 30.", "category": "math_trick", "difficulty": "easy"},
        {"question": "How many faces on a dodecahedron?", "answer": "12", "explanation": "Dodecahedron has twelve pentagonal faces.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What is the next prime after 7?", "answer": "11", "explanation": "8, 9, 10 are composite.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What is 111111111 x 111111111?", "answer": "12345678987654321", "explanation": "Pattern of multiplying repunits.", "category": "math_trick", "difficulty": "medium"},
        {"question": "How much dirt is in a hole 2x3x4 feet?", "answer": "None", "explanation": "A hole contains no dirt.", "category": "math_trick", "difficulty": "easy"},
        {"question": "Largest prime factor of 100?", "answer": "5", "explanation": "100 = 2^2 * 5^2.", "category": "math_trick", "difficulty": "medium"},
        {"question": "You drive 60 mph one way and 40 mph back the same distance. Average speed?", "answer": "48 mph", "explanation": "Harmonic mean of 60 and 40.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What comes next: 2, 6, 12, 20, 30, ?", "answer": "42", "explanation": "Differences increase by 2: n(n+1).", "category": "pattern", "difficulty": "easy"},
        {"question": "Complete: J, F, M, A, M, J, ?", "answer": "J", "explanation": "First letters of months: July.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: O, T, T, F, F, S, S, ?", "answer": "E", "explanation": "One, Two, Three... first letters.", "category": "pattern", "difficulty": "easy"},
        {"question": "Sequence: 1, 1, 2, 3, 5, 8, ?", "answer": "13", "explanation": "Fibonacci: sum previous two.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: 3, 3, 5, 4, 4, 3, 5, ?", "answer": "5", "explanation": "Letters in one, two, three...", "category": "pattern", "difficulty": "medium"},
        {"question": "Complete: 64, 32, 16, 8, ?", "answer": "4", "explanation": "Halve each term.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: AZ, BY, CX, ?", "answer": "DW", "explanation": "First letter advances, second retreats.", "category": "pattern", "difficulty": "medium"},
        {"question": "Sequence: 2, 3, 5, 7, 11, ?", "answer": "13", "explanation": "Prime numbers.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: 1, 4, 9, 16, 25, ?", "answer": "36", "explanation": "Perfect squares.", "category": "pattern", "difficulty": "easy"},
        {"question": "Complete: 5, 10, 20, 40, ?", "answer": "80", "explanation": "Double each term.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: ACE, BDF, CEG, ?", "answer": "DFH", "explanation": "Each letter shifts forward one.", "category": "pattern", "difficulty": "medium"},
        {"question": "Sequence: 1, 2, 6, 24, 120, ?", "answer": "720", "explanation": "Factorials: n!.", "category": "pattern", "difficulty": "medium"},
        {"question": "What comes next: 121, 144, 169, 196, ?", "answer": "225", "explanation": "Squares of 11, 12, 13, 14, 15.", "category": "pattern", "difficulty": "medium"},
        {"question": "Complete: Z, Y, X, W, V, ?", "answer": "U", "explanation": "Reverse alphabet.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: 0, 1, 1, 2, 4, 7, 13, ?", "answer": "24", "explanation": "Tribonacci: sum of previous three.", "category": "pattern", "difficulty": "hard"},
        {"question": "Sequence: 3, 6, 11, 18, 27, ?", "answer": "38", "explanation": "Add consecutive odd numbers.", "category": "pattern", "difficulty": "medium"},
        {"question": "What comes next: 1, 11, 21, 1211, 111221, ?", "answer": "312211", "explanation": "Look-and-say sequence.", "category": "pattern", "difficulty": "hard"},
        {"question": "Complete: A, D, G, J, ?", "answer": "M", "explanation": "Skip two letters each time.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: 2, 6, 18, 54, ?", "answer": "162", "explanation": "Multiply by 3.", "category": "pattern", "difficulty": "easy"},
        {"question": "Sequence: 1, 8, 27, 64, ?", "answer": "125", "explanation": "Cubes: n^3.", "category": "pattern", "difficulty": "easy"},
        {"question": "Complete: 100, 81, 64, 49, ?", "answer": "36", "explanation": "Descending perfect squares.", "category": "pattern", "difficulty": "medium"},
        {"question": "What comes next: 2, 5, 10, 17, 26, ?", "answer": "37", "explanation": "n^2 + 1 sequence.", "category": "pattern", "difficulty": "medium"},
        {"question": "Sequence: S, M, T, W, ?", "answer": "T", "explanation": "Days of week initials.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: 1, 2, 2, 4, 8, 32, ?", "answer": "256", "explanation": "Each term is product of previous two.", "category": "pattern", "difficulty": "hard"},
        {"question": "Complete: 2, 4, 8, 16, ?", "answer": "32", "explanation": "Powers of 2.", "category": "pattern", "difficulty": "easy"},
        {"question": "What comes next: A, Z, B, Y, C, X, ?", "answer": "D", "explanation": "Alternating from start and end of alphabet.", "category": "pattern", "difficulty": "medium"},
        {"question": "Sequence: 1, 4, 2, 5, 3, 6, ?", "answer": "4", "explanation": "Two interleaved sequences.", "category": "pattern", "difficulty": "medium"},
        {"question": "What comes next: Monday, Tuesday, Wednesday, ?", "answer": "Thursday", "explanation": "Days of the week.", "category": "pattern", "difficulty": "easy"},
        {"question": "Rearrange 'LISTEN' to form a word meaning 'silent'.", "answer": "SILENT", "explanation": "Anagram of LISTEN.", "category": "verbal", "difficulty": "easy"},
        {"question": "What word becomes shorter when you add two letters?", "answer": "Short", "explanation": "Adding 'er' makes 'shorter'.", "category": "verbal", "difficulty": "easy"},
        {"question": "Remove my first letter, I sound the same. Remove my last, still same. Remove both, still same. Word?", "answer": "Empty", "explanation": "Mpty, empt, mt all sound like empty.", "category": "verbal", "difficulty": "hard"},
        {"question": "Spell 'pots' backward. What do you do at a green light?", "answer": "Go", "explanation": "pots backward is stop—but at green you go.", "category": "verbal", "difficulty": "easy"},
        {"question": "What is the longest word in English?", "answer": "Smiles", "explanation": "There is a mile between first and last letter.", "category": "verbal", "difficulty": "easy"},
        {"question": "What word is always spelled wrong?", "answer": "Wrong", "explanation": "The word 'wrong' itself.", "category": "verbal", "difficulty": "easy"},
        {"question": "Rearrange 'DECIMAL POINT' to get a phrase about a number.", "answer": "I'm a dot in place", "explanation": "Anagram phrase.", "category": "verbal", "difficulty": "medium"},
        {"question": "What common word has three consecutive double letters?", "answer": "Bookkeeper", "explanation": "oo, kk, ee appear consecutively.", "category": "verbal", "difficulty": "hard"},
        {"question": "What word looks the same upside down?", "answer": "SWIMS", "explanation": "Capital letters form rotational symmetry.", "category": "verbal", "difficulty": "medium"},
        {"question": "What phrase has all five vowels in order?", "answer": "Facetious", "explanation": "Contains a,e,i,o,u in order.", "category": "verbal", "difficulty": "medium"},
        {"question": "What is the only common English word with two u's in a row?", "answer": "Vacuum", "explanation": "Double u in vacuum.", "category": "verbal", "difficulty": "easy"},
        {"question": "Rearrange 'DORMITORY' to describe a lazy student.", "answer": "Dirty room", "explanation": "Anagram.", "category": "verbal", "difficulty": "easy"},
        {"question": "What word starts with 'e', ends with 'e', and has one letter inside?", "answer": "Envelope", "explanation": "Envelope fits the description.", "category": "verbal", "difficulty": "easy"},
        {"question": "Name a word with no true vowels (a,e,i,o,u).", "answer": "Rhythm", "explanation": "Uses y as vowel sound; no aeiou.", "category": "verbal", "difficulty": "medium"},
        {"question": "What word is pronounced the same if you remove four letters?", "answer": "Queue", "explanation": "Remove ueue, still sounds like Q.", "category": "verbal", "difficulty": "easy"},
        {"question": "What is the only word that ends in 'mt'?", "answer": "Dreamt", "explanation": "Only common word ending in mt.", "category": "verbal", "difficulty": "medium"},
        {"question": "What letter of the alphabet contains the most water?", "answer": "C", "explanation": "Sea sounds like C.", "category": "verbal", "difficulty": "easy"},
        {"question": "Change one letter in 'COLD' to get a word describing warmth.", "answer": "Coal", "explanation": "Coal burns and produces heat.", "category": "verbal", "difficulty": "medium"},
        {"question": "How many edges does a cube have?", "answer": "12", "explanation": "Cube has 12 edges.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many faces does a cube have?", "answer": "6", "explanation": "Six square faces.", "category": "spatial", "difficulty": "easy"},
        {"question": "Fold a paper in half 3 times, cut one hole. How many holes when unfolded?", "answer": "8", "explanation": "Each fold doubles layers: 2^3 = 8.", "category": "spatial", "difficulty": "medium"},
        {"question": "Top view of a pyramid with square base?", "answer": "Square", "explanation": "Apex projects to center of base.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many vertices on an icosahedron?", "answer": "12", "explanation": "Regular icosahedron has 12 vertices.", "category": "spatial", "difficulty": "hard"},
        {"question": "Mirror reverses left-right but not up-down. Why?", "answer": "Front-back axis flip", "explanation": "Mirror reflects along axis perpendicular to glass.", "category": "spatial", "difficulty": "medium"},
        {"question": "Can you tile a floor with only regular pentagons?", "answer": "No", "explanation": "Pentagons alone cannot tile a plane.", "category": "spatial", "difficulty": "medium"},
        {"question": "How many colors minimum to color any map on a plane?", "answer": "4", "explanation": "Four color theorem.", "category": "spatial", "difficulty": "hard"},
        {"question": "A rope around Earth's equator. Add 1 meter. Can a cat slip under?", "answer": "Yes", "explanation": "Gap is about 1/(2*pi) meters, roughly 16 cm.", "category": "spatial", "difficulty": "hard"},
        {"question": "How many diagonals in a hexagon?", "answer": "9", "explanation": "n(n-3)/2 = 6*3/2 = 9.", "category": "spatial", "difficulty": "medium"},
        {"question": "Rotate letter 'b' 180 degrees. What do you get?", "answer": "q", "explanation": "Upside-down b resembles q.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many cubes in a 3x3x3 stack?", "answer": "27", "explanation": "3^3 = 27 unit cubes.", "category": "spatial", "difficulty": "easy"},
        {"question": "Slice a sphere with a flat plane. Cross-section shape?", "answer": "Circle", "explanation": "Any plane section of a sphere is a circle.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many edges on a tetrahedron?", "answer": "6", "explanation": "Four triangular faces, six edges.", "category": "spatial", "difficulty": "medium"},
        {"question": "Unfold a cube. How many distinct net patterns?", "answer": "11", "explanation": "Eleven distinct cube nets exist.", "category": "spatial", "difficulty": "hard"},
        {"question": "How many squares in a 3x3 grid?", "answer": "14", "explanation": "9 small + 4 medium + 1 large.", "category": "spatial", "difficulty": "medium"},
        {"question": "A cylindrical can. Is the label a rectangle or curved?", "answer": "Rectangle", "explanation": "Rectangular label wraps the curved surface.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many faces on an octahedron?", "answer": "8", "explanation": "Eight triangular faces.", "category": "spatial", "difficulty": "medium"},
        {"question": "Paper strip with half-twist glued. How many sides?", "answer": "1", "explanation": "Mobius strip has one side.", "category": "spatial", "difficulty": "medium"},
        {"question": "How many right angles in a rectangle?", "answer": "4", "explanation": "All four corners are 90 degrees.", "category": "spatial", "difficulty": "easy"},
        {"question": "View a coin from the edge. What shape?", "answer": "Rectangle", "explanation": "Edge-on view is rectangular.", "category": "spatial", "difficulty": "easy"},
        {"question": "How many vertices does a cube have?", "answer": "8", "explanation": "Eight corners.", "category": "spatial", "difficulty": "easy"},
        {"question": "Surface area of a unit cube?", "answer": "6", "explanation": "Six faces of area 1.", "category": "spatial", "difficulty": "medium"},
        {"question": "Angle between hour and minute hands at 3:15?", "answer": "7.5 degrees", "explanation": "Hour hand moves 7.5 degrees from 3 at quarter past.", "category": "spatial", "difficulty": "hard"},
        {"question": "Euler characteristic of a sphere?", "answer": "2", "explanation": "V - E + F = 2.", "category": "spatial", "difficulty": "medium"},
        {"question": "Flip 10 fair coins. Probability all heads?", "answer": "1/1024", "explanation": "Each flip 1/2; (1/2)^10.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "Two children; one is a boy born Tuesday. P(both boys)?", "answer": "About 13/27", "explanation": "Conditional probability with day constraint.", "category": "probability_paradox", "difficulty": "hard"},
        {"question": "Bertrand's box: gold-gold, silver-silver, gold-silver. Pick gold coin from random box. P(other is gold)?", "answer": "2/3", "explanation": "Not 1/2; Bayesian update favors gold-gold box.", "category": "probability_paradox", "difficulty": "hard"},
        {"question": "Simpson's paradox: can a treatment be worse in every subgroup but better overall?", "answer": "Yes", "explanation": "Aggregated trend can reverse subgroup trends.", "category": "probability_paradox", "difficulty": "hard"},
        {"question": "Gambler's fallacy: after 10 heads, P(next tails)?", "answer": "0.5", "explanation": "Coins have no memory.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "Birthday problem: minimum people for >50% shared birthday?", "answer": "23", "explanation": "Counterintuitively low.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Monty Hall after host opens goat: P(win if switch)?", "answer": "2/3", "explanation": "Switching doubles winning chance from 1/3.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Fair coin flipped until heads. P(exactly 3 flips)?", "answer": "1/8", "explanation": "Geometric: (1/2)^3.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Boy or girl paradox: one child is boy. P(both boys)?", "answer": "1/3", "explanation": "Sample space: BB, BG, GB (not GG).", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Three prisoners problem: one pardoned. Guard says another will die. Does P(you live) change?", "answer": "Yes, to 1/3", "explanation": "Conditional probability update.", "category": "probability_paradox", "difficulty": "hard"},
        {"question": "Law of large numbers: after 1000 heads, will next flip balance?", "answer": "No", "explanation": "Future flips remain independent at 50%.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "P(at least one six in four dice rolls)?", "answer": "About 52%", "explanation": "1 - (5/6)^4.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Two dice sum 7. P(doubles)?", "answer": "0", "explanation": "7 cannot be made with doubles.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "Drawing ace from shuffled deck?", "answer": "4/52 or 1/13", "explanation": "Four aces in fifty-two cards.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "Fair die rolled twice. P(sum is 7)?", "answer": "1/6", "explanation": "Six favorable pairs out of 36.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Russian roulette with 6-chamber revolver, one bullet. Spin, fire blank. Spin again or pull?", "answer": "Spin again", "explanation": "Spinning resets probability to 1/6 vs 1/5.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "100 prisoners, 100 boxes. Each opens 50. Strategy with >30% survival?", "answer": "Yes, follow cycles", "explanation": "Loop strategy yields about 31%.", "category": "probability_paradox", "difficulty": "hard"},
        {"question": "Flip fair coin 3 times. P(exactly 2 heads)?", "answer": "3/8", "explanation": "Three arrangements: HHT, HTH, THH.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Two fair coins. One lands heads. P(both heads)?", "answer": "1/3", "explanation": "Conditional on at least one head: HH, HT, TH.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Roll one die. P(odd number)?", "answer": "1/2", "explanation": "Three odd of six faces.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "Draw card, replace, draw again. P(two aces)?", "answer": "1/169", "explanation": "(4/52)^2.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "Coin flipped 3 times. P(at least one tail)?", "answer": "7/8", "explanation": "Only HHH fails: 1 - 1/8.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "P(two people in a group of 30 share a birthday?", "answer": "About 71%", "explanation": "Higher than the 23-person 50% case.", "category": "probability_paradox", "difficulty": "medium"},
        {"question": "What has no beginning, end, or middle?", "answer": "A circle", "explanation": "A circle is continuous with no endpoints.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "You see a boat full of people, yet there is not a single person on board. How?", "answer": "All are married", "explanation": "Not a single person—everyone is married.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "What can run but never walks, has a bed but never sleeps?", "answer": "A river", "explanation": "Rivers run and have riverbeds.", "category": "riddle", "difficulty": "easy"},
        {"question": "How do you make the number one disappear?", "answer": "Add 'g' to make 'gone'", "explanation": "One plus g spells gone.", "category": "verbal", "difficulty": "medium"},
        {"question": "What is half of 2 plus 2?", "answer": "3", "explanation": "Half of 2 is 1; 1 plus 2 equals 3.", "category": "math_trick", "difficulty": "easy"},
        {"question": "Sequence: 7, 10, 8, 11, 9, 12, ?", "answer": "10", "explanation": "Alternating +3 and -2.", "category": "pattern", "difficulty": "medium"},
        {"question": "If two's company and three's a crowd, what are four and five?", "answer": "Nine", "explanation": "Four plus five equals nine.", "category": "math_trick", "difficulty": "easy"},
        {"question": "What 3D shape rolls smoothly in any direction?", "answer": "Sphere", "explanation": "Sphere has uniform curvature in all directions.", "category": "spatial", "difficulty": "easy"},
        {"question": "You draw one card from a deck. P(red card)?", "answer": "1/2", "explanation": "Half the deck is red (hearts and diamonds).", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "A farmer has 17 sheep. All but 9 die. How many remain?", "answer": "9", "explanation": "All but nine means nine survive.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "What weighs more: a pound of feathers or a pound of bricks?", "answer": "Same", "explanation": "Both weigh one pound.", "category": "lateral_thinking", "difficulty": "easy"},
        {"question": "How many months have 28 days?", "answer": "All 12", "explanation": "Every month has at least 28 days.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "What comes next: I, II, III, IV, ?", "answer": "V", "explanation": "Roman numerals.", "category": "pattern", "difficulty": "easy"},
        {"question": "Rearrange NEW DOOR to one word.", "answer": "ONE WORD", "explanation": "Anagram of NEW DOOR.", "category": "verbal", "difficulty": "medium"},
        {"question": "How many triangles in a pentagram?", "answer": "35", "explanation": "Count all sizes in the star figure.", "category": "spatial", "difficulty": "hard"},
        {"question": "Expected value of fair die roll?", "answer": "3.5", "explanation": "Average of 1 through 6.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "What has a bottom at the top?", "answer": "Your legs", "explanation": "Your bottom is at the top of your legs.", "category": "riddle", "difficulty": "medium"},
        {"question": "Divide 30 by half and add 10. Result?", "answer": "70", "explanation": "30 divided by 0.5 is 60; plus 10 is 70.", "category": "math_trick", "difficulty": "medium"},
        {"question": "What comes next: North, East, South, ?", "answer": "West", "explanation": "Cardinal directions clockwise.", "category": "pattern", "difficulty": "easy"},
        {"question": "Can a man marry his widow's sister?", "answer": "No", "explanation": "If she is a widow, he is dead.", "category": "logic_puzzle", "difficulty": "easy"},
        {"question": "How many seconds in a year?", "answer": "12", "explanation": "One per month: 2nd of January, etc.", "category": "verbal", "difficulty": "hard"},
        {"question": "What shape has four equal sides but not necessarily right angles?", "answer": "Rhombus", "explanation": "All sides equal; angles need not be 90 degrees.", "category": "spatial", "difficulty": "medium"},
        {"question": "P(sum of two dice is 2)?", "answer": "1/36", "explanation": "Only double ones.", "category": "probability_paradox", "difficulty": "easy"},
        {"question": "What invention allows you to look right through a solid wall?", "answer": "Window", "explanation": "Windows are transparent openings.", "category": "riddle", "difficulty": "easy"},
        {"question": "Complete: 3, 9, 27, 81, ?", "answer": "243", "explanation": "Multiply by 3 each time.", "category": "pattern", "difficulty": "easy"},
        {"question": "What is always answered even when never asked?", "answer": "A doorbell", "explanation": "Doorbells get responses without questions.", "category": "lateral_thinking", "difficulty": "medium"},
        {"question": "How many 9s between 1 and 100?", "answer": "20", "explanation": "9 appears 20 times in that range.", "category": "math_trick", "difficulty": "hard"},
        {"question": "What word becomes its opposite when you remove its first two letters?", "answer": "Stable", "explanation": "Remove 'un' from 'unstable'.", "category": "verbal", "difficulty": "hard"},
        {"question": "Volume of sphere radius r formula?", "answer": "4/3 pi r^3", "explanation": "Standard sphere volume formula.", "category": "spatial", "difficulty": "medium"},
        {"question": "Three fair coins. P(at least two heads)?", "answer": "1/2", "explanation": "HHT, HTH, THH, HHH: four of eight.", "category": "probability_paradox", "difficulty": "medium"},
    ]
    from training.cognitive_bank.shape_patterns import build_shape_brain_teasers

    raw.extend(build_shape_brain_teasers())
    return raw
