# Generated by Django 5.1.15 on 2026-08-28 22:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("focus", models.CharField(blank=True, max_length=200)),
                ("objectives", models.TextField(blank=True)),
                ("target_minutes", models.PositiveIntegerField(default=180)),
                ("completed", models.BooleanField(default=False)),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                (
                    "score",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("maximum_score", models.FloatField(default=100)),
                (
                    "percentage",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in minutes"
                    ),
                ),
                ("mistakes", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("solved", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time in minutes", null=True
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("question", models.TextField()),
                (
                    "ideal_topics",
                    models.TextField(blank=True, help_text="Topics to cover in answer"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "difficulty"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="training_in_categor_6bc2a5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterviewAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.interviewquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("repository_url", models.URLField(blank=True)),
                ("deployed_url", models.URLField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Language"),
                            ("algorithms", "Algorithms"),
                            ("backend", "Backend"),
                            ("database", "Database"),
                            ("infrastructure", "Infrastructure"),
                            ("architecture", "Architecture"),
                            ("testing", "Testing"),
                            ("cloud", "Cloud"),
                            ("ai", "AI"),
                            ("soft_skills", "Soft Skills"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_score",
                    models.FloatField(
                        default=8.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "current_score",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="training_sk_slug_d281b3_idx"),
                    models.Index(
                        fields=["category"], name="training_sk_categor_8a709e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mistake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("knowledge_gap", "Knowledge Gap"),
                            ("careless_error", "Careless Error"),
                            ("algorithmic_error", "Algorithmic Error"),
                            ("syntax_error", "Syntax Error"),
                            ("debugging_error", "Debugging Error"),
                            ("time_management", "Time Management"),
                            ("communication", "Communication"),
                            ("architecture", "Architecture"),
                            ("database", "Database"),
                            ("testing", "Testing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mistakes",
                        to="training.assessment",
                    ),
                ),
                (
                    "coding_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mistakes",
                        to="training.codingproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mistakes",
                        to="training.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="training.skill",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("study", "Study"),
                            ("coding", "Coding"),
                            ("project", "Project"),
                            ("assessment", "Assessment"),
                            ("reading", "Reading"),
                            ("interview", "Interview"),
                            ("review", "Review"),
                            ("debugging", "Debugging"),
                            ("system_design", "System Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=30)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("blocked", models.BooleanField(default=False)),
                ("blocked_reason", models.TextField(blank=True)),
                ("skipped", models.BooleanField(default=False)),
                ("skip_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="training.skill",
                    ),
                ),
                (
                    "training_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="training.trainingday",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="training.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="training.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wins", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("tomorrow_focus", models.TextField(blank=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="training.trainingday",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("current_streak", models.PositiveSmallIntegerField(default=0)),
                ("longest_streak", models.PositiveSmallIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("program_start_date", models.DateField(blank=True, null=True)),
                ("total_study_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("objectives", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="training.phase",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
            },
        ),
        migrations.AddField(
            model_name="trainingday",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="training.week",
            ),
        ),
        migrations.CreateModel(
            name="WeeklyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("tasks_total", models.PositiveIntegerField(default=0)),
                ("study_minutes", models.PositiveIntegerField(default=0)),
                ("assessment_percentage", models.FloatField(default=0.0)),
                ("strongest_skill", models.CharField(blank=True, max_length=100)),
                ("weakest_skill", models.CharField(blank=True, max_length=100)),
                ("repeated_mistake", models.TextField(blank=True)),
                ("learned", models.TextField(blank=True)),
                ("difficult", models.TextField(blank=True)),
                ("went_well", models.TextField(blank=True)),
                ("improve", models.TextField(blank=True)),
                ("next_week_focus", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="training.week",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codingproblem",
            index=models.Index(
                fields=["user", "solved"], name="training_co_user_id_81d39d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingproblem",
            index=models.Index(
                fields=["user", "category"], name="training_co_user_id_e4cbf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingproblem",
            index=models.Index(
                fields=["difficulty"], name="training_co_difficu_f02098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewattempt",
            index=models.Index(
                fields=["user", "needs_review"], name="training_in_user_id_80de49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewattempt",
            index=models.Index(
                fields=["user", "created_at"], name="training_in_user_id_4ce6b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mistake",
            index=models.Index(
                fields=["user", "resolved"], name="training_mi_user_id_cbf80a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mistake",
            index=models.Index(
                fields=["user", "category"], name="training_mi_user_id_eea4fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["user", "completed_at"], name="training_as_user_id_927f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["user", "category"], name="training_as_user_id_0132fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "started_at"], name="training_st_user_id_38a410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "is_active"], name="training_st_user_id_342a0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["completed"], name="training_ta_complet_734215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type"], name="training_ta_task_ty_523516_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["training_day", "completed"],
                name="training_ta_trainin_b85b0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreview",
            index=models.Index(
                fields=["user", "created_at"], name="training_da_user_id_324c50_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreview",
            unique_together={("user", "training_day")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="training_us_user_id_16cf3c_idx"),
        ),
        migrations.AddIndex(
            model_name="week",
            index=models.Index(
                fields=["week_number"], name="training_we_week_nu_89b1f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("phase", "week_number")},
        ),
        migrations.AddIndex(
            model_name="trainingday",
            index=models.Index(
                fields=["day_number"], name="training_tr_day_num_18dc86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingday",
            index=models.Index(fields=["date"], name="training_tr_date_c853f4_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingday",
            index=models.Index(
                fields=["completed"], name="training_tr_complet_77177e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingday",
            unique_together={("week", "day_number")},
        ),
        migrations.AlterUniqueTogether(
            name="weeklyreview",
            unique_together={("user", "week")},
        ),
    ]
