# Generated by Django 5.1.15 on 2026-08-28 22:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def clear_legacy_interview_data(apps, schema_editor):
    InterviewAttempt = apps.get_model("training", "InterviewAttempt")
    InterviewQuestion = apps.get_model("training", "InterviewQuestion")
    InterviewAttempt.objects.all().delete()
    InterviewQuestion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_slug", models.SlugField()),
                ("unlocked_through_order", models.PositiveIntegerField(default=1)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="interviewquestion",
            options={"ordering": ["section_slug", "order"]},
        ),
        migrations.AddField(
            model_name="interviewattempt",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="hints",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="learning_objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("expert", "Expert"),
                    ("elite", "Elite"),
                ],
                default="beginner",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="min_pass_score",
            field=models.FloatField(
                default=6.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="section_slug",
            field=models.SlugField(default="python"),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="solution_code",
            field=models.TextField(
                blank=True, help_text="Reference solution with comments"
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="solution_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="time_estimate_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddIndex(
            model_name="interviewquestion",
            index=models.Index(
                fields=["section_slug"], name="training_in_section_53e839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewquestion",
            index=models.Index(
                fields=["section_slug", "order"], name="training_in_section_72b184_idx"
            ),
        ),
        migrations.RunPython(clear_legacy_interview_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="interviewquestion",
            constraint=models.UniqueConstraint(
                fields=("section_slug", "order"), name="unique_section_question_order"
            ),
        ),
        migrations.AddField(
            model_name="practiceprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="practiceprogress",
            index=models.Index(
                fields=["user", "section_slug"], name="training_pr_user_id_95a39a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="practiceprogress",
            unique_together={("user", "section_slug")},
        ),
    ]
