# Generated by Django 5.1.15 on 2026-08-28 22:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_practiceprogress_alter_interviewquestion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineeringChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("lab", "Lab"),
                            ("benchmark", "Benchmark"),
                            ("debugging", "Debugging"),
                            ("system_design", "System Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="Steps or code scaffold"),
                ),
                ("solution_notes", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=45)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["challenge_type", "order"],
                "indexes": [
                    models.Index(
                        fields=["challenge_type"], name="training_en_challen_694c49_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CareerGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("category", models.CharField(default="learning", max_length=50)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "target_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "completed"],
                        name="training_ca_user_id_65f9ee_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EngineeringAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("time_minutes", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.engineeringchallenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="training_en_user_id_e301ca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wishlist", "Wishlist"),
                            ("applied", "Applied"),
                            ("interviewing", "Interviewing"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="training_jo_user_id_d5447b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("concept", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("next_review", models.DateField()),
                ("interval_days", models.PositiveIntegerField(default=1)),
                ("repetition", models.PositiveIntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_cards",
                        to="training.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review"],
                "indexes": [
                    models.Index(
                        fields=["user", "next_review"],
                        name="training_re_user_id_43bea8_idx",
                    )
                ],
            },
        ),
    ]
