# Generated by Django 5.1.15 on 2026-08-29 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0011_mock_coding_tests"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cognitiveprogress",
            new_name="training_co_user_id_b5d164_idx",
            old_name="training_co_user_id_2e8f44_idx",
        ),
        migrations.RenameIndex(
            model_name="cognitivequestion",
            new_name="training_co_challen_fd83c3_idx",
            old_name="training_co_challen_91a2b1_idx",
        ),
        migrations.RenameIndex(
            model_name="cognitivequestion",
            new_name="training_co_challen_87cab0_idx",
            old_name="training_co_challen_4c8e22_idx",
        ),
        migrations.RenameIndex(
            model_name="cognitivequestion",
            new_name="training_co_challen_d653ea_idx",
            old_name="training_co_challen_7f3a19_idx",
        ),
        migrations.RenameIndex(
            model_name="engineeringlabsession",
            new_name="training_en_user_id_cd1ce3_idx",
            old_name="training_en_user_id_8a1f2c_idx",
        ),
        migrations.RenameIndex(
            model_name="mockinterviewquestion",
            new_name="training_mo_round_i_3132de_idx",
            old_name="training_mo_round_i_4a8f21_idx",
        ),
        migrations.RenameIndex(
            model_name="mockinterviewsession",
            new_name="training_mo_user_id_ddb072_idx",
            old_name="training_mo_user_id_91c2a4_idx",
        ),
        migrations.RenameIndex(
            model_name="mockinterviewsession",
            new_name="training_mo_user_id_5ee956_idx",
            old_name="training_mo_user_id_2b7e18_idx",
        ),
        migrations.AlterField(
            model_name="mockinterviewresponse",
            name="score",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
