# Generated by Django 5.1.15 on 2026-08-29 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training",
            "0012_rename_training_co_user_id_2e8f44_idx_training_co_user_id_b5d164_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("checked_criteria", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("deployed_url", models.URLField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="project",
            name="acceptance_criteria",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"id": "ac-1", "text": "...", "required": true}',
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="architecture_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="deliverables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("expert", "Expert"),
                ],
                default="hard",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_hours",
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="project",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="functional_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="getting_started",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_catalog",
            field=models.BooleanField(
                default=False,
                help_text="Published in the Projects hub (curriculum / portfolio briefs)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="learning_outcomes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="milestones",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="non_functional_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="overview",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tagline",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="week_focus",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Suggested curriculum week", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_catalog", "order"], name="training_pr_is_cata_555156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="training_pr_slug_ce5cb2_idx"),
        ),
        migrations.AddField(
            model_name="projectprogress",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_rows",
                to="training.project",
            ),
        ),
        migrations.AddField(
            model_name="projectprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectprogress",
            index=models.Index(
                fields=["user", "status"], name="training_pr_user_id_0e3504_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectprogress",
            unique_together={("user", "project")},
        ),
    ]
