# Generated by Django 5.1.15 on 2026-09-02 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0013_project_catalog_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("docs", "Official docs"),
                            ("course", "Course"),
                            ("video", "Video"),
                            ("book", "Book"),
                            ("tool", "Tool"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "day_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional curriculum day this resource supports.",
                        null=True,
                    ),
                ),
                (
                    "week_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight as the first recommended read for the skill/day.",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="training.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "indexes": [
                    models.Index(
                        fields=["day_number"], name="training_le_day_num_b53463_idx"
                    ),
                    models.Index(
                        fields=["skill", "order"], name="training_le_skill_i_93f935_idx"
                    ),
                    models.Index(
                        fields=["resource_type"], name="training_le_resourc_03304b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("url", "day_number", "skill"),
                        name="uniq_resource_url_day_skill",
                    )
                ],
            },
        ),
    ]
