# Generated by Django 5.1.15 on 2026-09-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0014_learning_resources_and_phase4"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivequestion",
            name="choices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Multiple-choice options, e.g. [{"key":"A","text":"□"}, ...]',
            ),
        ),
    ]
