# Generated by Django 5.1.15 on 2026-09-02 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0015_cognitive_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_digest_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekdays", "Weekdays only"),
                    ("weekly", "Weekly (Mondays)"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_reminder_hour",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Local hour (0–23) to send the digest.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_reminders_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Send coaching digests about sessions, progress, and reading.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
